import Head from "next/head";
import styles from "@/styles/pages/index.module.css";
import { useState } from "react";

export default function Index() {
  const [input, setInput] = useState('');

  return (
    <>
      <Head>
        <title>Urna DFM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <main>
          <div className={styles.screen}>
            {input}
          </div>
        </main>
        <aside>
          <div className={styles.buttons}>
            <button onClick={() => setInput(current => current+'1')}>
              1
            </button>
            <button  onClick={() => setInput(current => current+'2')}>
              2
            </button>
            <button  onClick={() => setInput(current => current+'3')}>
              3
            </button>
            <button  onClick={() => setInput(current => current+'4')}>
              4
            </button>
            <button  onClick={() => setInput(current => current+'5')}>
              5
            </button>
            <button  onClick={() => setInput(current => current+'6')}>
              6
            </button>
            <button  onClick={() => setInput(current => current+'7')}>
              7
            </button>
            <button  onClick={() => setInput(current => current+'8')}>
              8
            </button>
            <button  onClick={() => setInput(current => current+'9')}>
              9
            </button>
            <div />
            <button  onClick={() => setInput(current => current+'0')}>
              0
            </button>
            <div />
            <button style={{backgroundColor:"white", color: "black"}}>
              BRANCO
            </button>
            <button style={{backgroundColor:"red"}} onClick={() => setInput('')}>
              CORRIGE
            </button>
            <button style={{backgroundColor:"green"}}>
              CONFIRMA
            </button>
          </div>
        </aside>
      </main>
    </>
  );
}
